spring.application.name=TrabalhoBackEnd_computer


spring.data.mongodb.uri=mongodb://localhost:27017/dbapplication
spring.data.mongodb.auto-index-creation=true

#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=dbapplication
#spring.data.mongodb.username=myuser
#spring.data.mongodb.password=mypassword